name: money
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # แนะนำให้ระบุช่วงที่กว้างขึ้นเล็กน้อยแต่ยังคงความเข้ากันได้

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 # For iOS style icons

  # Local Database (SQLite)
  sqflite: ^2.3.3+1             # SQLite plugin for Flutter
  path_provider: ^2.1.3       # For accessing file system paths (to store database file)
  path: ^1.9.0                # For path manipulation (often used with sqflite)

  # File Handling & Permissions
  file_picker: ^10.1.9         # For user to pick files (import/export)
  permission_handler: ^11.3.1  # For requesting permissions (e.g., storage access)

  # Data Encryption & Hashing
  encrypt: ^5.0.3             # For encrypting/decrypting data files
  bcrypt: ^1.1.3              # For securely hashing PINs

  # Sharing
  share_plus: ^11.0.0         # For sharing files via OS share sheet
  shared_preferences: ^2.2.2

  # State Management
  # provider: ^6.1.2 # Alternative state management
  flutter_riverpod: ^2.5.1    # Recommended for versatile state management

  # Utility
  uuid: ^4.4.0                # For generating Unique IDs
  intl: ^0.20.0               # For date and number formatting
  package_info_plus: ^8.3.0   # For retrieving app version information

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0       # Recommended lints for Flutter
  # isar_generator: ^3.1.0+1    # Removed - No longer using Isar
  # build_runner: ^2.4.13       # Removed - Not strictly needed for sqflite unless using other generators

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
